version: '3.7'

services:
  jenkins:
    restart: always
    image: whatwewant/jenkins:${SERVICE_JENKINS_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_JENKINS_PORT}:80
    volumes:
      - ${SERVICE_DATA}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/dock.sock

networks:
  default:
    external: true
    name: compose-ingress
