version: '3.7'

services:
  jenkins:
    restart: always
    image: whatwewant/jenkins:${SERVICE_JENKINS_IMAGE_VERSION}
    # user: jenkins:${DOCKER_GROUP_ID}
    # privileged: true
    # user: root
    ports:
      # - 0.0.0.0:${SERVICE_JENKINS_PORT}:80
      - 0.0.0.0:${SERVICE_JENKINS_PORT}:8080
      # - 0.0.0.0:${SERVICE_JENKINS_PORT}:50000
      # - 0.0.0.0:${SERVICE_JENKINS_PORT}:10051
    volumes:
      - ${SERVICE_DATA}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
    # environment:
    #  DOCKER_HOST: unix:///var/run/dock.sock # @TODO will cause docker connect error

networks:
  default:
    external: true
    name: compose-ingress
